# Generated by Django 5.0.4 on 2024-04-17 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courtName', models.TextField()),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Mcourt', to='BadmintonCourt.court')),
                ('user', models.OneToOneField(limit_choices_to={'groups__name': 'Members'}, on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('court', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Ncourt', to='BadmintonCourt.court')),
            ],
        ),
    ]
