# Generated by Django 5.0.4 on 2024-04-17 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BadmintonCourt', '0002_alter_mbooking_court'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbooking',
            name='court',
            field=models.OneToOneField(limit_choices_to={'available': True}, on_delete=django.db.models.deletion.CASCADE, related_name='Mcourt', to='BadmintonCourt.court'),
        ),
    ]
