# Generated by Django 5.0.4 on 2024-04-17 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BadmintonCourt', '0004_alter_nbooking_court'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbooking',
            name='user',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Members'}, on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
