# Generated by Django 5.0.4 on 2024-04-17 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BadmintonCourt', '0005_alter_mbooking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbooking',
            name='court',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Mcourt', to='BadmintonCourt.court'),
        ),
        migrations.AlterField(
            model_name='nbooking',
            name='court',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Ncourt', to='BadmintonCourt.court'),
        ),
    ]
